spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/everest?useSSL=false
    username: root
    password: root

welcome:
  message: Hello From Pramod Nikam